[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@chainlink/contracts/src/=lib/chainlink-brownie-contracts/contracts/src/"]
# remappings = ["@chainlink/contracts/src/v0.8/shared/interfaces/ = /lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces/"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
